Increment08
IgorAleksandroff/musthave-devops pull request #10
Opened 2022-08-02 18:06 UTC by IgorAleksandroff

2022-08-05 01:00 UTC, capsulated requested changes
Есть некоторые замечания в части организации пакетов приложения. Необходимо их организовать по примеру стандартных пакетов go.

Текстом этот момент намного сложнее описать, да и не очень понятно будет. Поэтому предлагаю 1to1.

Также, определение хендлеров необходимо перенести из cmd в пакет, который связан с этими хендлерами.

2022-08-05 01:00 UTC, capsulated commented on cmd/server/main.go
> +	config := server.GetConfig()
Конфиг лучше вынести в отдельный пакет, так как там не только конфигурация сервера может быть, но и конфиги для других сущностей.

2022-08-05 01:00 UTC, capsulated commented on cmd/agent/main.go
> +	config := client.GetConfig()
Конфиг(и) лучше вынести в отдельный пакет

2022-08-05 01:00 UTC, capsulated commented on cmd/server/main.go
> +	config := server.GetConfig()
Конфиг(и) лучше вынести в отдельный пакет.

Так как, также, могут быть конфиги для других сущностей, помимо server и client

2022-08-05 01:00 UTC, capsulated commented on cmd/agent/main.go
> +	defer reportTicker.Stop()
А эти defer сработают? )

2022-08-05 01:00 UTC, capsulated commented on cmd/server/main.go
> +	server.AddHandler(http.MethodPost, "/update/{TYPE}/{NAME}/{VALUE}", metricHandler.HandleMetricPost)
Назначение обработчиков роутера лучше перенести в пакет сервера. Перенести в конструктор или отдельным пакетом. Если обработчиков не много, то функция-конструктор Server'а отлично подходит для этого.

2022-08-05 01:00 UTC, capsulated commented on internal/api/server.go
> +const (
Все переменные конфига необходимо "отсоединить" от реализации сервера. Отдельный пакет, где происходит чтение и вся обработка конфигов - стандартная практика конфигурирования приложения / вебсервисов.

2022-08-05 01:00 UTC, capsulated commented on internal/api/server.go
>  type Handler interface {
Хэндлер можно не выносить в отдельный пакет. Он относиться к серверу, поэтому лучше сделать его частью пакета Server.

2022-08-05 01:00 UTC, capsulated commented on internal/pkg/metricscollection/entity/metric.go
> +type Metrics struct {
Дублируется код Metrics. Это неправильно. Принцип Don't Repeat Yourself (DRY).

metricscollection т runtimemetrics - это логически одна сущность, поэтому делить её на два пакета не стоит.

2022-08-05 01:00 UTC, capsulated commented on internal/pkg/metricscollection/entity/metric.go
> +package entity
**pkg** отдельный пакет внутри **api**. В принципе, это лишнее.
В го очень интересная особенность: папка является пакетом. То есть, это отдельная независимая сущность. Чем больше папок мы создаём - тем больше пакетов в нашей программе. К пакетам необходимо относиться также, как к структурам - это общая область видимости для всего внутри пакета. Для **go** все файлы в одной папке являются логически одним файлом. А каждый пакет - это что-то типа независимого модуля. Поэтому нужно с осторожностью создавать папки и не стоит создавать их большое количество. Минимальная вложенность и создание новых папок (пакетов) только в случае острой необходимости.

Как пример, можно посмотреть исходный код стандартных библиотек **go**.

2022-08-05 01:00 UTC, capsulated commented on internal/pkg/metricscollection/entity/metric.go
> +package entity
Использование общих слов в неймнге пакетов и переменных - плохая практика. Это я про entity. Нужно подбирать что-то однозначное, что точно обозначит сущность. Назвать метод / структуру / переменную так, чтобы не нужно было писать комментарий к ней, чтобы по названию сразу было понятно что и делает и за что ответсвенна сущность.

2022-08-09 17:58 UTC, IgorAleksandroff commented on internal/pkg/metricscollection/entity/metric.go
> +package entity
config вынес в отдельный пакет. 
роутинг перенес в конструктор сервера. 
убрал лишние пакеты и объединил файлы хендлера.

2022-08-09 19:14 UTC, capsulated approved these changes
В принципе, всё классно.

В некоторых методах, которые возвращают **error**, нужно всё же обязательно обрабатывать ошибки. В нашем примере, конечно, ошибок не возникнет, но в реальных проектах разные данные прийти могут.

Методты, типа reader.Decode, io.Write и тп.

Проверь плиз, а в следующем спринте проверим.

2022-08-11 14:43 UTC, merged