Sprint04
IgorAleksandroff/musthave-devops pull request #21
Opened 2022-08-29 16:51 UTC by IgorAleksandroff

* асинхронное сохранение и тправка метрика на авгенте

* добавлены util метрики

* инициализация DB внутри конструктора

* избавление от utils

Co-authored-by: Igor Aleksandrov <ivaleksandrov@avito.ru>

2022-08-31 13:56 UTC, capsulated requested changes
Большая вложенность пакетов. Необходимо уменьшить количество папок (так как это пакеты).

К примеру: 
1) `metrichandler` перенести на уровень `internal`. И в ней не создавать доп папок
2) `enviroment` также, либо в один пакет, либо два разных. На данный момент: один пакет `enviroment`, и два пакета внутри
3) `pkg` пакет создаётся на уровне `internal`, как противопоставление этому `internal`, то есть пакеты, предназначенные для импорта в других приложениях. Всё что в папке `pkg` нужно либо перенести в `internal`, либо `pkg` вынести на уровень `internal`
4) В `metricscollection` два разных пакеты с одинаковыми конструкторами. Лучше заменить их названия а сами `repositorymemo` и `repositorypg` перенести на уровень `internal`. Нужно подумать, может сделать один пакет для двух этих сущностей? В пакете может быть несколько структур - это ок. А `entity` можно перенести в отдельный пакет
5) `NewPinger` возвращает `*rep`. Зачем отдельная структура `*rep`? `pinger` нужно привязать в репозиторию постгреса. И если зочеться использовать в нейминге именно `repository`, то хотя бы добавлять префикс/постфикс что это за репозиторий. А вообще, лучше постфикс `repository`, если очень хочется использовать этот паттерн
6) Использование `Usecase`, в принципе, оправдано использованием паттерна, но название общиее. По-моему мнению, оно подходит для примера, а в реальном проекте `UseCase` нужно однозначно назвать по тому кейсу использования, что он делает.

2022-08-31 13:56 UTC, capsulated commented on cmd/server/main.go
> +		repositoryPG, err := repositorypg.NewRepository(ctx, config.AddressDB)
Создание репозитория в зависимости от конфига нужно перенести в конструктор репозитоия

2022-09-01 19:33 UTC, capsulated requested changes
Я посмотрел видео про паттерн **repository/usecase**. Если есть время и желание, то можно созвониться. Я бы мог сопоставить то, что рассказывают в видео с тем, что мы пишем. А также ещё свои мысли рассказать. Но решение о результате нужно проговорить.
Если сложно со временем, то я могу принять PR, но созвониться и обсудить, что в данном проекте покрывает этот шаблон, а что из шаблона будет лишним. Микросервис, который мы пишем в инкрементах совсем небольшой, поэтому некоторая часть, описанная патерном, в нашем случае будет избыточной.
Так же, расскажу своё мнение, чтобы я взял из этого паттерна, а что нет, если будет интересно.
О решении пиши в директ слака. Если захочешь оставить как есть, совзонимся, расскажешь свою точку зрения, отправлишь и я сразу заапрувлю.

2022-09-04 19:23 UTC, capsulated approved these changes
В принципе всё ок!

Апрувлю. Пару замечаний написал

2022-09-04 19:23 UTC, capsulated commented on cmd/server/main.go
> +	metricsUC, err := metricscollection.NewMetricsCollection(ctx, metricscollection.Config{
`metricscollection.Config` структуру нужно создавать в `ServerConfig`

2022-09-04 19:23 UTC, capsulated commented on internal/metricscollection/usecase.go
> +	Config struct {
Плохо, что есть тип `Config` в этом  пакете. Его лучше в пакет конфиг переместить

2022-09-04 19:23 UTC, capsulated commented on internal/metricscollection/usecase.go
> +	if cfg.AddressDB != "" {
👍

2022-09-04 19:23 UTC, capsulated commented on metrichandler/handler.go
> +package metrichandler
Можно просто `handler` назвать. А даже наверное `router` и `methods`. Но два файла `handle` и `handler` добавляют сложность в понимании. А в принципе,  одного файлика было бы достаточно

2022-09-05 15:51 UTC, IgorAleksandroff commented on internal/metricscollection/usecase.go
> +	Config struct {
Согласен, лучше все конфиги хранить в одном пакете.

2022-09-05 15:51 UTC, merged